apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: LoadBalancer
  selector:
    app: api
  ports:
    - name: private-api
      protocol: TCP
      port: 4000
      targetPort: 4000
    - name: public-api
      protocol: TCP
      port: 3000
      targetPort: 3000
    - name: websocket
      protocol: TCP
      port: 3005
      targetPort: 3005
