apiVersion: v1
kind: Service
metadata:
  name: transactions-processor-service
spec:
  type: LoadBalancer
  selector:
    app: transactions-processor
  ports:
    - name: transactions-processor
      protocol: TCP
      port: 5202
      targetPort: 5202
