{
 "title": "Template Service",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "6s",
 "panels": [
  {
   "title": "Processing Time [1 min interval]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(endpoint) (delta(api_cpu_time_sum[1m])) / 1000",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "API Calls / second",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by() (delta(api_count[1m])) / 60"
    }
   ]
  },
  {
   "title": "Average Response Time [1 min interval]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by(endpoint) (delta(api_sum[1m])) / sum by(endpoint) (delta(api_count[1m]))",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "CPU Time [1 min interval]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(endpoint) (delta(api_sum[1m])) / 1000",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "API Calls / Second [1 min interval]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(endpoint) (rate(api_count{code=~\"200|201|304\"}[1m]))",
     "legendFormat": "{{endpoint}} "
    }
   ]
  },
  {
   "title": "Average CPU Time [1 min interval]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by(endpoint) (delta(api_cpu_time_sum[1m])) / sum by(endpoint) (delta(api_cpu_time_count[1m]))",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "External API Avg Response time [ms]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (system) (delta(external_apis_sum{}[1m])) / sum by (system) (delta(external_apis_count{}[1m]))",
     "legendFormat": "{{system}}"
    }
   ]
  },
  {
   "title": "Nodejs CPU Load [1 min interval]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "delta(process_cpu_seconds_total[1m]) / 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cached API Hits [1 min interval]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(endpoint) (delta(cached_api_hits[1m]))",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Redis Processing Seconds [1 min interval]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (action) (delta(redis_duration_sum{}[1m])) / 1000",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "External API Calls / Second [1 min interval]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(system) (rate(external_apis_count[1m]))",
     "legendFormat": "{{system}}"
    }
   ]
  },
  {
   "title": "Average Redis Response Time [1 min interval]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (action) (delta(redis_duration_sum{}[1m])) / sum by (action) (delta(redis_duration_count{}[1m]))",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Redis Calls / s [1 min interval]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (action) (rate(redis_duration_count{}[1m]))",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Jobs Execution Duration [10 min interval]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(job_identifier) (rate(jobs_sum[10m]))",
     "legendFormat": "{{job_identifier}}"
    }
   ]
  },
  {
   "title": "Jobs Execution Percentage [60 min interval]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (job_identifier) (rate(jobs_sum{}[60m])) / 3600",
     "legendFormat": "{{job_identifier}}"
    }
   ]
  },
  {
   "title": "Transactions value [6 sec interval]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum by(shardId) (transactions_total_value)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}