apiVersion: v1
kind: Service
metadata:
  name: cache-warmer-service
spec:
  type: LoadBalancer
  selector:
    app: cache-warmer
  ports:
    - name: cache-warmer
      protocol: TCP
      port: 5201
      targetPort: 5201