apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
  labels:
    app: grafana
data:
  prometheus.yaml: |
{{ .Files.Get "../../../monitoring/grafana/datasources/prometheus.yml" | indent 2 }}